# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:

    runs-on: ubuntu-latest
    defaults:
      run:
    

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: orders-dashboard-frontend/package-lock.json
      - run: npm ci
        working-directory: ./orders-dashboard-frontend
      - run: npm run build --if-present
        working-directory: ./orders-dashboard-frontend
      - run: npm start &
        working-directory: ./orders-dashboard-frontend
    
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build and test with Maven
        run: mvn clean test

      - name: Close ng
        run: pkill -f ng
